<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="assets\characters\default_female\animations\walk\gifs\walk_down.gif" />
    <None Remove="assets\characters\default_female\animations\walk\gifs\walk_down_left.gif" />
    <None Remove="assets\characters\default_female\animations\walk\gifs\walk_down_right.gif" />
    <None Remove="assets\characters\default_female\animations\walk\gifs\walk_left.gif" />
    <None Remove="assets\characters\default_female\animations\walk\gifs\walk_right.gif" />
    <None Remove="assets\characters\default_female\animations\walk\gifs\walk_up.gif" />
    <None Remove="assets\characters\default_female\animations\walk\gifs\walk_up_left.gif" />
    <None Remove="assets\characters\default_female\animations\walk\gifs\walk_up_right.gif" />
    <None Remove="assets\characters\default_female\idle\idle_down.png" />
    <None Remove="assets\characters\default_female\idle\idle_down_left.png" />
    <None Remove="assets\characters\default_female\idle\idle_down_right.png" />
    <None Remove="assets\characters\default_female\idle\idle_left.png" />
    <None Remove="assets\characters\default_female\idle\idle_right.png" />
    <None Remove="assets\characters\default_female\idle\idle_up.png" />
    <None Remove="assets\characters\default_female\idle\idle_up_left.png" />
    <None Remove="assets\characters\default_female\idle\idle_up_right.png" />
    <None Remove="assets\characters\default_male\animations\run\run_east.gif" />
    <None Remove="assets\characters\default_male\animations\walk\gifs\walk_down.gif" />
    <None Remove="assets\characters\default_male\animations\walk\gifs\walk_down_left.gif" />
    <None Remove="assets\characters\default_male\animations\walk\gifs\walk_down_right.gif" />
    <None Remove="assets\characters\default_male\animations\walk\gifs\walk_left.gif" />
    <None Remove="assets\characters\default_male\animations\walk\gifs\walk_right.gif" />
    <None Remove="assets\characters\default_male\animations\walk\gifs\walk_up.gif" />
    <None Remove="assets\characters\default_male\animations\walk\gifs\walk_up_left.gif" />
    <None Remove="assets\characters\default_male\animations\walk\gifs\walk_up_right.gif" />
    <None Remove="assets\characters\default_male\idle\idle_down.png" />
    <None Remove="assets\characters\default_male\idle\idle_down_left.png" />
    <None Remove="assets\characters\default_male\idle\idle_down_right.png" />
    <None Remove="assets\characters\default_male\idle\idle_left.png" />
    <None Remove="assets\characters\default_male\idle\idle_right.png" />
    <None Remove="assets\characters\default_male\idle\idle_up.png" />
    <None Remove="assets\characters\default_male\idle\idle_up_left.png" />
    <None Remove="assets\characters\default_male\idle\idle_up_right.png" />
    <None Remove="assets\images\fulbank_go_back_logo.jpg" />
    <None Remove="assets\images\fulbank_home_page.jpg" />
    <None Remove="assets\images\fulbank_login_page.png" />
    <None Remove="assets\images\seemless_loading_screen.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="assets\characters\default_female\animations\walk\gifs\walk_down.gif" />
    <Resource Include="assets\characters\default_female\animations\walk\gifs\walk_down_left.gif" />
    <Resource Include="assets\characters\default_female\animations\walk\gifs\walk_down_right.gif" />
    <Resource Include="assets\characters\default_female\animations\walk\gifs\walk_left.gif" />
    <Resource Include="assets\characters\default_female\animations\walk\gifs\walk_right.gif" />
    <Resource Include="assets\characters\default_female\animations\walk\gifs\walk_up.gif" />
    <Resource Include="assets\characters\default_female\animations\walk\gifs\walk_up_left.gif" />
    <Resource Include="assets\characters\default_female\animations\walk\gifs\walk_up_right.gif" />
    <Resource Include="assets\characters\default_female\idle\idle_down.png" />
    <Resource Include="assets\characters\default_female\idle\idle_down_left.png" />
    <Resource Include="assets\characters\default_female\idle\idle_down_right.png" />
    <Resource Include="assets\characters\default_female\idle\idle_left.png" />
    <Resource Include="assets\characters\default_female\idle\idle_right.png" />
    <Resource Include="assets\characters\default_female\idle\idle_up.png" />
    <Resource Include="assets\characters\default_female\idle\idle_up_left.png" />
    <Resource Include="assets\characters\default_female\idle\idle_up_right.png" />
    <Resource Include="assets\characters\default_male\animations\run\run_east.gif" />
    <Resource Include="assets\characters\default_male\animations\walk\gifs\walk_down.gif" />
    <Resource Include="assets\characters\default_male\animations\walk\gifs\walk_down_left.gif" />
    <Resource Include="assets\characters\default_male\animations\walk\gifs\walk_down_right.gif" />
    <Resource Include="assets\characters\default_male\animations\walk\gifs\walk_left.gif" />
    <Resource Include="assets\characters\default_male\animations\walk\gifs\walk_right.gif" />
    <Resource Include="assets\characters\default_male\animations\walk\gifs\walk_up.gif" />
    <Resource Include="assets\characters\default_male\animations\walk\gifs\walk_up_left.gif" />
    <Resource Include="assets\characters\default_male\animations\walk\gifs\walk_up_right.gif" />
    <Resource Include="assets\characters\default_male\idle\idle_down.png" />
    <Resource Include="assets\characters\default_male\idle\idle_down_left.png" />
    <Resource Include="assets\characters\default_male\idle\idle_down_right.png" />
    <Resource Include="assets\characters\default_male\idle\idle_left.png" />
    <Resource Include="assets\characters\default_male\idle\idle_right.png" />
    <Resource Include="assets\characters\default_male\idle\idle_up.png" />
    <Resource Include="assets\characters\default_male\idle\idle_up_left.png" />
    <Resource Include="assets\characters\default_male\idle\idle_up_right.png" />
    <Resource Include="assets\images\fulbank_go_back_logo.jpg" />
    <Resource Include="assets\images\fulbank_home_page.jpg" />
    <Resource Include="assets\images\fulbank_login_page.png" />
    <Resource Include="assets\images\seemless_loading_screen.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="assets\characters\three_piece_man\animations\gifs\" />
  </ItemGroup>

</Project>
